### ISSUE TITLE
ERROR: custom_idle_queue_1.default is not a constructor

### ISSUE THREAD

**Issue by leonardotdleal** [pubkey/custom-idle-queue#2]
Hello. On our team we are using the `custom-idle-queue` and we got a problem with `IdleQueue` import.

**angular and typescript versions**:
```
"@angular/cli": "1.6.5"
"@angular": "5.2.1"
"typescript": "2.6.2"
```

We created an angular service that instantiate `IdleQueue`.

**sample.service.ts**:
```
import IdleQueue from 'custom-idle-queue';
...
private idleQueue = new IdleQueue();
```

When we try to reference this service that uses `custom-idle-queue`.

**app.component.ts**:
```
export class AppComponent {
  constructor(storage: SampleService) { }
}
```

It throws the following error in the console:

**Console**:
> ERROR TypeError: custom_idle_queue_1.default is not a constructor
    at new SampleService (sample.service.ts:8)

**Comment by pubkey** [comment]
Can you try `import * as IdleQueue from 'custom-idle-queue';`

**Comment by leonardotdleal** [comment]
I tried to do it but it doesn't work, I still see the same error.

It only works when I transpile it to javascript, but I need it to work in typescript code as well.

**Comment by pubkey** [comment]
The [default export is a class](https://github.com/pubkey/custom-idle-queue/blob/master/src/index.d.ts#L24). Can you change the typings-file in you `node_modules/custom-idle-queue` to make it work?

**Comment by leonardotdleal** [comment]
Hello @pubkey 

It worked with the following implementation.
I changed the import as suggested, assigned to a constant with any type and in the initialization of IdleQueue I used that constant.

Code:
```
import * as IdleQueue from 'custom-idle-queue';
...
const _IdleQueue: any = IdleQueue;
...
private idleQueue = new _IdleQueue();
```

Thanks!

**Comment by pubkey** [comment]
@leonardotdleal nice that this works for you. But you are basically disabling typescript which should never be done. Your `idleQueue` will be of type `any`.

I think this is a problem by custom-idle-queue which should be fixed here.

**Comment by leonardotdleal** [comment]
@pubkey if you fix it would be best for us.

We can wait for the `custom-idle-queue` to update in our project.

**Comment by pubkey** [comment]
@leonardotdleal please update to `2.1.2`, might work now.

**Comment by pubkey** [comment]
Should work now. Please reooen if it doesnt.
